name: Deploy SSH
on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Deploy
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Kill previous screen session
      run: |
        screen -XS mysession quit || true
      if: always()
      
    - name: Start new process
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GEMINI_API: ${{ secrets.GEMINI_API }}
        LIMIT_USE: ${{ secrets.LIMIT_USE }}
        VIDEOG_DB: ${{ secrets.VIDEOG_DB }}
        SAUCENAO: ${{ secrets.SAUCENAO }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        echo "Iniciando el Server"
        screen -dmS mysession python main.py
      if: always()