name: Deploy SSH
on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Deploy
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        echo "Calvooo"
        #python main.py